BNT:
  cl_BNT_transform: false
  cov_BNT_transform: false
C_ell:
  cl_CCL_kwargs:
    l_limber: -1
    limber_integration_method: spline
    non_limber_integration_method: FKEM
  cl_GG_path: ../data/data_sb/cl_gg_tab.txt
  cl_GL_path: ../data/data_sb/cl_gl_tab.txt
  cl_LL_path: ../data/data_sb/cl_ll_tab.txt
  gal_bias_table_filename: ../data/data_sb/gal_bias.txt
  galaxy_bias_fit_coeff:
  - 1.33291
  - -0.72414
  - 1.0183
  - -0.14913
  has_IA: false
  has_magnification_bias: false
  has_rsd: false
  mag_bias_table_filename: ./input/mag_bias.txt
  magnification_bias_fit_coeff:
  - -1.50685
  - 1.35034
  - 0.08321
  - 0.04279
  mult_shear_bias:
  - 0
  - 0
  use_input_cls: true
  which_gal_bias: from_input
  which_mag_bias: FS2_polynomial_fit
PyCCL:
  cov_integration_method: spline
  gsl_params: null
  load_cached_tkka: true
  n_samples_wf: 1000
  spline_params:
    A_SPLINE_NA_PK: 240
    K_MAX_SPLINE: 300
  use_default_k_a_grids: false
cosmology:
  N_eff: 3.046
  ODE: 0.68
  Ob: 0.05
  Om: 0.32
  Om_k0: 0
  h: 0.6737
  m_nu: 0.06
  ns: 0.966
  s8: 0.816
  wa: 0.0
  wz: -1.0
covariance:
  G: true
  SSC: false
  cNG: false
  cov_filename: cov_{which_ng_cov:s}_{probe:s}_{ndim}.npz
  covariance_ordering_2D: ell_probe_zpair
  include_b2g: true
  include_terasawa_terms: false
  k_steps: 100
  load_cached_sigma2_b: false
  log10_k_max: 2
  log10_k_min: -5
  no_sampling_noise: true
  row_col_major: row-major
  save_full_cov: true
  sigma2_b_integration_scheme: levin
  sigma_eps_i: 0.0
  split_gaussian_cov: false
  triu_tril: triu
  use_KE_approximation: true
  which_b1g_in_resp: from_input
  which_pk_responses: halo_model
  z_max: 3.0
  z_min: 0.02
  z_steps: 7000
  z_steps_trisp: 50
ell_binning:
  binning_type: unbinned
  ell_bins_GC: 29
  ell_bins_WL: 29
  ell_bins_ref: 32
  ell_max_GC: 256
  ell_max_WL: 256
  ell_max_ref: 5000
  ell_min_GC: 0
  ell_min_WL: 0
  ell_min_ref: 10
extra_parameters:
  camb:
    HMCode_logT_AGN: 7.75
    dark_energy_model: ppf
    halofit_version: mead2020_feedback
    kmax: 100
    num_massive_neutrinos: 1
halo_model:
  concentration: ConcentrationDuffy08
  halo_bias: HaloBiasTinker10
  halo_profile_dm: HaloProfileNFW
  halo_profile_hod: HaloProfileHOD
  mass_def: MassDef200m
  mass_function: MassFuncTinker10
intrinsic_alignment:
  Aia: 0.16
  CIA: 0.0134
  bIA: 0.0
  eIA: 1.66
  lumin_ratio_filename: null
  z_pivot_IA: 0
mask:
  apodize: false
  aposize: 0.1
  generate_polar_cap: true
  load_mask: false
  mask_path: ../input/mask.fits
  nside: 1024
  survey_area_deg2: 13245
misc:
  levin_batch_size: 1000
  num_threads: 40
  output_path: ../data/data_sb
  test_cholesky_decomposition: false
  test_condition_number: false
  test_numpy_inversion: false
  test_symmetry: false
namaster:
  coupled_cov: false
  spin0: false
  use_INKA: true
  use_namaster: false
  workspace_path: '...'
nz:
  clip_zmax: 3
  clip_zmin: 0
  dzGC:
  - 0.0
  - 0.0
  dzWL:
  - 0.0
  - 0.0
  ngal_lenses:
  - 10.0
  - 10.0
  ngal_sources:
  - 10.0
  - 10.0
  normalize_shifted_nz: true
  nz_lenses_filename: ../data/data_sb/nz_pos_fmt.txt
  nz_sources_filename: ../data/data_sb/nz_she_fmt.txt
  shift_nz: false
probe_selection:
  GG: true
  GL: true
  LL: true
  cross_cov: true
sample_covariance:
  compute_sample_cov: false
  fix_seed: true
  nreal: 5000
  which_cls: namaster
